print("Help me make a recipe!")
print()
print()
food = input("Name a food > ")
plant = input("Name a type of plant > ")
method = input("Name a method of cooking > ")
burned = input("What word describes burned food? > ")
householdItem = input("Name a household item > ")
print()
print()
print()
print("====Today's Menu!====")
print()
print(method, food, "with", burned, plant, "on a bed of", householdItem)