print("\033[35m", "==Welcome to your adventure simulator!==", "\033[0m")
print("I am going to ask you a bunch of questions, and then create an", "\033[32m", "epic", "\033[0m", "story, with you as the", "\033[33m", "star!", "\033[0m")
print()
print()
name = input("What's your name?  >  ")
enemy = input("What's your worst enemy's name?  >  ")
superPower = input("What is your superpower?  >  ")
live = input("Where do you live?  >  ")
food = input("What is your favorite food?  >  ")
print()
print()
print("\033[31m", "Loading Story...", "\033[0m")
print()
print()
print("Hello", name, "! Your ability to", superPower, "will make you never have to look at", enemy, "again. Go eat", food, "as you walk down the streets of", live, "and use", superPower, "for", "\033[32m", "good","\033[0m" "and not evil!")
print("\033[m")